export const topScorers = [
  { name: 'Marcelo Rocha Ferreira', countGols: 2, team: 'Juventus'},
  { name: 'Marcones Fernandes da S. Filho', countGols: 2, team: 'Pasta'},
  { name: 'Ricardis (Reforço)', countGols: 3, team: 'Cruz Azul'},
  { name: 'Matheus (Reforço)', countGols: 2, team: 'Assentamento (Sta. Tereza)'},
  { name: 'Matheus Victor (Reforço)', countGols: 2, team: 'Cachoeirinha'},
  { name: 'Francisco Valdeci da Silva', countGols: 1, team: 'Assentamento (Sta. Tereza)'},
  { name: 'Francisco Valdeci da Silva', countGols: 1, team: 'Assentamento (Sta. Tereza)'},
  { name: 'Antônio Alano César Jorge', countGols: 1, team: 'Cangati'},
  { name: 'Manoel Eduardo Pinheiro Paz', countGols: 1, team: 'Cangati'},
  { name: 'Francisco Erison Pinheiro', countGols: 1, team: 'Juventus'},
  { name: 'Francisco A. D. Peixoto', countGols: 1, team: 'Juventus'},
  { name: 'Luiz Fernando Cândido Diniz', countGols: 1, team: 'Plejusc'},
  { name: 'Francisco Ernivaldo de Lima', countGols: 1, team: 'Plejusc'},
  { name: 'Theimo (Reforço)', countGols: 1, team: 'Barra Nova'},
  { name: 'Lucas (Reforço)', countGols: 1, team: 'Cangati'},
  { name: 'João Paulo (Reforço)', countGols: 1, team: 'Cruz Azul'},
  { name: 'Francisco Anderson (Reforço)', countGols: 1, team: 'Cruz Azul'},
  { name: 'Antonio D. de L. Nascimento', countGols: 1, team: 'Cruz Azul'},
  { name: 'Gean c. de L. A. (Reforço)', countGols: 1, team: 'Juventus'},
  { name: 'Antonio U. de S. L. (Reforço)', countGols: 1, team: 'Juventus'},
  { name: 'Igor Alves de Lima (Reforço)', countGols: 1, team: 'Juventus'},
  { name: 'Charles Miller (Reforço)', countGols: 1, team: 'Trem das Onze'},
  { name: 'Gabriel Palmiere (Reforço)', countGols: 1, team: 'Trem das Onze'},
  { name: 'Cicero S. S. F. (Reforço)', countGols: 1, team: 'Cachoeirinha'},
  { name: 'Pedro H. C. (Reforço)', countGols: 1, team: 'Juventus'},
  { name: 'João Victor Souza Freitas', countGols: 1, team: 'Pasta'},
  { name: 'Denilson (Reforço)', countGols: 1, team: 'Assentamento (Sta. Tereza)'},
  { name: 'Julinho (Reforço)', countGols: 1, team: 'Trem das Onze'},
  { name: 'Francisco A. D. Peixoto', countGols: 1, team: 'Juventus'},
  { name: 'Francisco C. de B. Neto (Reforço)', countGols: 1, team: 'Cangati'},
  { name: 'Romário C. da S. (Reforço)', countGols: 1, team: 'Cangati'},
  { name: 'Anderson Wilinny (Reforço)', countGols: 1, team: 'Cachoeirinha'},
  { name: 'Léo Irapuan (Reforço)', countGols: 1, team: 'Juventus'},
  { name: 'Kate (Reforço)', countGols: 1, team: 'Assentamento (Sta. Tereza)'},
  { name: 'Rulieu de Souza Silva', countGols: 1, team: 'Assentamento (Sta. Tereza)'},
  { name: 'Antonio I. R. de A. (Reforço)', countGols: 1, team: 'Juventus'},
  { name: 'Cicero (Reforço)', countGols: 1, team: 'Trem das Onze'},
]